from coinbase.websocket import WSClient
import threading
from collections import deque
from queue import Queue 
import json
from decimal import Decimal
import storage
import sqlite3
from datetime import datetime, timezone




class dataReceiver:
    def __init__(self, product_id: str, batch_size: int = 1000, session_label: str = ""):
        self.product_id: str = product_id    # ie "BTC-USD"
        self.session_id: int | None = None   # generated by sqlite
        self.session_label: str = session_label
        self.row_id: int = 0   # increments one for each row we send to db
        self.message_id: int = 0

        self.messages: Queue = Queue()
        self.batch: list = []
        self.batch_size: int = batch_size

    def on_message(self, msg):
        self.messages.put(json.loads(msg))

    def next_row_id(self):
        row_id = self.row_id
        self.row_id += 1
        return row_id

    def next_message_id(self):
        message_id = self.message_id
        self.message_id += 1
        return message_id

    def fetch_updates(self):
        client = WSClient(on_message=self.on_message)
        client.open()

        try: 
            client.level2(product_ids=[self.product_id])
            client.heartbeats()

            while True:
                command = input("Type stop to finish: ")

                if command.strip().lower() == "stop":
                    break

        finally:
            client.close()


    def process_message(self, msg: dict, connection):
        # message should have a channel, we want to process is == "l2_data"
        
        if msg.get("channel") != "l2_data":
            return

        msg_id: int = self.next_message_id()
        event_index = 0
        # extract the individual events
        for event in msg["events"]:
            for update in event["updates"]:
                row_id: int = self.next_row_id()
                row = (
                    row_id, 
                    self.session_id,
                    msg_id,
                    event_index,
                    event["product_id"],
                    event["type"],
                    update["event_time"],
                    update["side"],
                    update["price_level"],
                    update["new_quantity"],
                )
                self.batch.append(row)
                if len(self.batch) >= self.batch_size:
                    storage.insert_events_batch(connection, self.batch)
                    self.batch.clear()


            event_index += 1
        
        pass

    def process_updates(self):
        '''
        Establishes connection to the database, adds in a session row
        then tries to process each message'''
        connection = sqlite3.connect("market_data.db")

        try:
            # Create the session row
            self.session_id = storage.insert_session(
                connection,
                (
                    self.session_label,
                    self.product_id,
                    datetime.now(timezone.utc).isoformat(),
                ),
            )

            while True:
                msg = self.messages.get()
                try:
                    # we send in None as the last message after closing coinbase connection
                    if msg is None:
                        break
                    self.process_message(msg, connection)

                finally:
                    self.messages.task_done()   # need to tell the thread its finished

            if self.batch:
                storage.insert_events_batch(connection=connection, batch=self.batch)
                self.batch.clear()

        finally:
            connection.close()



    def run(self):
        '''Starts the processing thread then starts fetch updates,
        type stop to end the collection'''
        processor = threading.Thread(target=self.process_updates)
        processor.start()

        try:
            self.fetch_updates()

        finally:
            self.messages.put(None)
            processor.join()
            finish = datetime.now(timezone.utc).isoformat()

        connection = sqlite3.connect("market_data.db")
        try:
            count = storage.count_session_rows(connection, self.session_id)
            print(f"Session {self.session_id}: {count} rows saved.")
            snapshot_count = storage.count_session_rows(connection, self.session_id, "snapshot")
            update_count = storage.count_session_rows(connection, self.session_id, "update")
            print(snapshot_count, update_count)
            storage.finish_collection(connection, session_id=self.session_id, 
                                           snapshot_count=snapshot_count, 
                                           update_count=update_count,
                                           message_count=self.message_id
                                           )
        finally:
            connection.close()


